name: GetScreen Windows (6H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=casiosatrianaliqa@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://raw.githubusercontent.com/CasTzz/rdp/main/bin/down.bat" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
